"""
Data loading utilities.
Supports the Kaggle SMS Spam Collection format:
  - columns: v1 (ham/spam label), v2 (message text)
  - OR: label, text (already cleaned)
"""

import logging
import pandas as pd

from spamdet.config import (
    RAW_CSV, PROCESSED_CSV,
    TEXT_COLUMN, LABEL_COLUMN,
    DATA_PROCESSED_DIR,
)

logger = logging.getLogger(__name__)


# ── Public API ────────────────────────────────────────────────────────────────

def load_raw(path=RAW_CSV) -> pd.DataFrame:
    """Load the raw CSV and normalise column names."""
    logger.info("Loading raw data from %s", path)

    df = pd.read_csv(path, encoding="latin-1")

    # Handle Kaggle SMS Spam format (v1 / v2 / extra unnamed cols)
    if "v1" in df.columns and "v2" in df.columns:
        df = df[["v1", "v2"]].rename(columns={"v1": LABEL_COLUMN, "v2": TEXT_COLUMN})
    elif "Category" in df.columns and "Masseges" in df.columns:
        df = df[["Category", "Masseges"]].rename(columns={"Category": LABEL_COLUMN, "Masseges": TEXT_COLUMN})
    elif LABEL_COLUMN in df.columns and TEXT_COLUMN in df.columns:
        df = df[[LABEL_COLUMN, TEXT_COLUMN]]
    else:
        raise ValueError(
            f"Expected columns ('v1','v2') or ('{LABEL_COLUMN}','{TEXT_COLUMN}'). "
            f"Got: {list(df.columns)}"
        )

    logger.info("Raw data shape: %s", df.shape)
    return df


def load_processed(path=PROCESSED_CSV) -> pd.DataFrame:
    """Load the pre-processed CSV (generated by preprocessing.py)."""
    logger.info("Loading processed data from %s", path)
    df = pd.read_csv(path)
    logger.info("Processed data shape: %s", df.shape)
    return df


def save_processed(df: pd.DataFrame, path=PROCESSED_CSV) -> None:
    """Persist the cleaned DataFrame to disk."""
    DATA_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    logger.info("Saved processed data → %s", path)
